//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public string vDecisionID { get; set; }
        public string vAgendaID { get; set; }
        public string vDecisionDetails { get; set; }
        public int iIndex { get; set; }
    
        public virtual MeetingAgenda MeetingAgenda { get; set; }
    }
}
