//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingInvite
    {
        public string vMeetingInviteID { get; set; }
        public string vMeetingID { get; set; }
        public string Id { get; set; }
        public int iIndex { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
