//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingTask()
        {
            this.TaskAssigns = new HashSet<TaskAssign>();
        }
    
        public string vTaskID { get; set; }
        public string vAgendaID { get; set; }
        public string vTaskDetails { get; set; }
        public int iIndex { get; set; }
    
        public virtual MeetingAgenda MeetingAgenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssign> TaskAssigns { get; set; }
    }
}
