//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MeetingAgendas = new HashSet<MeetingAgenda>();
            this.MeetingInvites = new HashSet<MeetingInvite>();
        }
    
        public string vMeetingID { get; set; }
        public string Id { get; set; }
        public string vTitle { get; set; }
        public System.DateTime dDate { get; set; }
        public System.TimeSpan tStartTime { get; set; }
        public System.TimeSpan tEndTime { get; set; }
        public string vLocation { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAgenda> MeetingAgendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingInvite> MeetingInvites { get; set; }
    }
}
